- name: install nginx
  package:
    name: 
      - nginx
      - nginx-extras
    state: present
  notify: restart nginx

- name: disable default configuration
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: create nginx forwarding rules
  template:
    src: site-forwards
    dest: "/etc/nginx/sites-available/site-forwards"
  notify: restart nginx

- name: harden nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: enable nginx forwarding rules
  file:
    src: /etc/nginx/sites-available/site-forwards
    dest: /etc/nginx/sites-enabled/site-forwards
    state: link
  notify: restart nginx

- name: check if default certificate exist
  stat:
    path: /etc/nginx/ssl/defaultnginx.crt
  register: cert_stat
  tags: cert-defaul

- name: copy default certificate for default page
  copy:
    src: files/nginx-default-cert/defaultnginx.crt
    dst: /etc/nginx/ssl/defaultnginx.crt
  when: not cert_stat.stat.exist
  tags: cert-defaul

- name: copy default key for certificat for default page
  copy:
    src: files/nginx-default-cert/defaultnginx.key
    dst: /etc/nginx/ssl/defaultnginx.key
  when: not cert_stat.stat.exist
  notify: restart nginx
  tags: cert-defaul
